# Generated by Django 2.1.3 on 2020-05-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_novels_images_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Novels',
        ),
    ]
