# Generated by Django 2.1.3 on 2020-05-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_novels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('resume', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='images')),
            ],
        ),
    ]
